services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    environment:
      - N8N_HOST=integra.devinfinite.cloud
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://integra.devinfinite.cloud/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true

    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/files

    ports:
      - "5678:5678"

volumes:
  n8n_data:
