version: '3.8'

services:
  consul-server-1:
    image: hashicorp/consul:latest
    hostname: consul-server-1
    restart: always
    container_name: consul-server-1
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500" # UI, API
      - "8600:8600/udp" # DNS
    volumes:
      - 'consul-server-1-data:/consul/data'
      - './config/consul-config.hcl:/consul/config/consul-config.hcl' # Monta o arquivo de configuração HCL
    command:
      - consul
      - agent
      - -server
      - -bootstrap-expect=2
      - -ui
      - -node=consul-server-1
      - -client=0.0.0.0
      - -data-dir=/consul/data
      - -retry-join=consul-server-2
      - -encrypt=${CONSUL_ENCRYPT_KEY}
      - -config-dir=/consul/config # Aponta para o diretório de configuração
    networks:
      - infra
      - traefik-network
    labels:
      - "traefik.enable=true"
      # Rota externa segura com seu domínio de produção
      - "traefik.http.routers.consul.rule=Host(`consul.devinfinite.cloud`)"
      - "traefik.http.routers.consul.entrypoints=websecure"
      - "traefik.http.routers.consul.tls.certresolver=leresolver"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
      
      # Middleware CORS para permitir que aplicações frontend façam leitura
      - "traefik.http.middlewares.consul-cors.headers.accesscontrolallowmethods=GET,OPTIONS"
      - "traefik.http.middlewares.consul-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.consul-cors.headers.accesscontrolallowheaders=X-Consul-Token,Content-Type"
      - "traefik.http.routers.consul.middlewares=consul-cors"

  consul-server-2:
    image: hashicorp/consul:latest
    hostname: consul-server-2
    restart: always
    container_name: consul-server-2
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - 'consul-server-2-data:/consul/data'
      - './config/consul-config.hcl:/consul/config/consul-config.hcl' # Monta o arquivo de configuração HCL
    command:
      - consul
      - agent
      - -server
      - -bootstrap-expect=2
      - -node=consul-server-2
      - -client=0.0.0.0
      - -data-dir=/consul/data
      - -retry-join=consul-server-1
      - -encrypt=${CONSUL_ENCRYPT_KEY}
      - -config-dir=/consul/config # Aponta para o diretório de configuração
    networks:
      - infra
      - traefik-network

  # Container temporário apenas para criar as permissões automaticamente
  consul-init:
    image: curlimages/curl:latest
    container_name: consul-init
    depends_on:
      - consul-server-1
    volumes:
      - './config/init-acl.sh:/init-acl.sh'
    command: ["sh", "/init-acl.sh"]
    networks:
      - infra

networks:
  infra:
    external: true
  traefik-network:
    external: true

volumes:
  consul-server-1-data:
  consul-server-2-data: