services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    container_name: 'datascience-notebook'
    restart: always
    ports:
      - '4000:4000'
    networks:
      app_net:
        ipv4_address: 172.20.3.33


networks:
  app_net:
    name: network_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
