services:
  portainer:
    image: big-agi:latest
    container_name: 'big_chatgpt'
    restart: always
    ports:
      - '1212:3000'
    networks:
      app_net:
        ipv4_address: 172.20.3.2


networks:
  app_net:
    name: network_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
